# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Killshot < Formula
  desc "Killshot CLI — code analysis"
  homepage "https://killshot.io"
  version "0.1.0"
  license "PROPRIETARY"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Killshot-AI-Tool/killshot/releases/download/v0.1.0/killshot_0.1.0_darwin_amd64.tar.gz"
      sha256 "35c2a877e06b9e6cfdfa0028602c48dda061f3be6212e6b388c1d647f69459a4"

      define_method(:install) do
        bin.install "killshot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Killshot-AI-Tool/killshot/releases/download/v0.1.0/killshot_0.1.0_darwin_arm64.tar.gz"
      sha256 "ae4415c3292b3bd5040fe0f7b51916e1a7a2bb1d03d433ddd2f50301868f0f7d"

      define_method(:install) do
        bin.install "killshot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Killshot-AI-Tool/killshot/releases/download/v0.1.0/killshot_0.1.0_linux_amd64.tar.gz"
      sha256 "1d85e5400b05fbcd0863880b195fd22815e400a50d14136ff859d77a87eea2f8"
      define_method(:install) do
        bin.install "killshot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Killshot-AI-Tool/killshot/releases/download/v0.1.0/killshot_0.1.0_linux_arm64.tar.gz"
      sha256 "c67567e96d8640cbbe94b4a34354537ed40823be8ede78917af7bac4d464db00"
      define_method(:install) do
        bin.install "killshot"
      end
    end
  end

  test do
    system "#{bin}/killshot", "version"
  end
end
