# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Killshot < Formula
  desc "Killshot CLI — code analysis"
  homepage "https://killshot.io"
  version "0.1.0"
  license "PROPRIETARY"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.killshot.io/0.1.0/killshot_0.1.0_darwin_amd64.tar.gz"
      sha256 "d89bd20cbcbef32227cc4c9f5d635b47762491604d03c3db46c96a9e27fe6737"

      define_method(:install) do
        bin.install "killshot"
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.killshot.io/0.1.0/killshot_0.1.0_darwin_arm64.tar.gz"
      sha256 "8111aa14a98bf791c4f1acbc1e0c19cae7d6a04c058789769c9749c09971e7d9"

      define_method(:install) do
        bin.install "killshot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://dl.killshot.io/0.1.0/killshot_0.1.0_linux_amd64.tar.gz"
      sha256 "038fa9cfb2da5dc4db3e395db025a2abcfa9d7bc555b18ae21b2eb54622ddf82"
      define_method(:install) do
        bin.install "killshot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://dl.killshot.io/0.1.0/killshot_0.1.0_linux_arm64.tar.gz"
      sha256 "79459b35330d8ba7fe30c43ba3eea3897824cbdec998af0969892796836da809"
      define_method(:install) do
        bin.install "killshot"
      end
    end
  end

  test do
    system "#{bin}/killshot", "version"
  end
end
