# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Killshot < Formula
  desc "Killshot CLI — code analysis"
  homepage "https://killshot.io"
  version "0.1.1"
  license "PROPRIETARY"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.killshot.io/0.1.1/killshot_0.1.1_darwin_amd64.tar.gz"
      sha256 "cc2e174061d3964a45b7ad215bcb61b9a8cb4225c855244028a2c4e168cb9ee5"

      define_method(:install) do
        bin.install "killshot"
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.killshot.io/0.1.1/killshot_0.1.1_darwin_arm64.tar.gz"
      sha256 "a6df2a5b4de600707f2a19ca81cde544b715d72ed7a0d6b6c5bb1e12f74b4a74"

      define_method(:install) do
        bin.install "killshot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://dl.killshot.io/0.1.1/killshot_0.1.1_linux_amd64.tar.gz"
      sha256 "c61ae58e78f6db9e9f2f54ef21424a88519a8c5dcef938978cd18a8178c62138"
      define_method(:install) do
        bin.install "killshot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://dl.killshot.io/0.1.1/killshot_0.1.1_linux_arm64.tar.gz"
      sha256 "7ff539e421af858d299f1350cdc000f1fcb22f6c6e108161a174f780119fe663"
      define_method(:install) do
        bin.install "killshot"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/killshot version")
  end
end
